# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        # The default build is so verbose the travis log file can exceed the allowed limit.
        # Run a custom install that hides all the Maven ‘Downloading’ messages.
        # Also skip signing artifacts here as gpg is not enable on travis ci
        mvn install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -Dgpg.skip=true -V -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
        mvn clean install sonar:sonar -Dgpg.skip=true
